export const snapshot: any = {
  store: {
    "document:document": {
      gridSize: 10,
      name: "",
      meta: {},
      id: "document:document",
      typeName: "document",
    },
    "page:page": {
      meta: {},
      id: "page:page",
      name: "Page 1",
      index: "a1",
      typeName: "page",
    },
    "shape:7ylVcTF9O9Dw-zzMQeyCu": {
      x: 1003.475038048274,
      y: 269.4778763691605,
      rotation: 0,
      isLocked: false,
      opacity: 1,
      meta: {},
      id: "shape:7ylVcTF9O9Dw-zzMQeyCu",
      type: "arrow",
      parentId: "page:page",
      index: "a3",
      props: {
        dash: "draw",
        size: "m",
        fill: "none",
        color: "black",
        labelColor: "black",
        bend: 0,
        start: {
          type: "binding",
          boundShapeId: "shape:c0xymhguNAIgUyUF7cGNY",
          normalizedAnchor: {
            x: 0.4866677212921222,
            y: 0.8634641469464348,
          },
          isPrecise: true,
          isExact: false,
        },
        end: {
          type: "point",
          x: 25.000963302295077,
          y: 189.8627269678861,
        },
        arrowheadStart: "none",
        arrowheadEnd: "arrow",
        text: "Start chat Here",
        labelPosition: 0.5,
        font: "draw",
      },
      typeName: "shape",
    },
    "shape:LowB4-z1Azjp7mk7sQg5j": {
      x: 97.18795532270991,
      y: 664.3869259741732,
      rotation: 6.265732014659643,
      isLocked: false,
      opacity: 1,
      meta: {},
      id: "shape:LowB4-z1Azjp7mk7sQg5j",
      type: "text",
      props: {
        color: "black",
        size: "m",
        w: 395.52555864780146,
        text: "Tired of having long chat histories and being unable to make sense of what prompts you have given, try branc",
        font: "draw",
        align: "middle",
        autoSize: false,
        scale: 1,
      },
      parentId: "page:page",
      index: "a5",
      typeName: "shape",
    },
    "shape:c0xymhguNAIgUyUF7cGNY": {
      x: 783.5246158590064,
      y: 192.91894120375525,
      rotation: 0,
      isLocked: false,
      opacity: 1,
      meta: {},
      id: "shape:c0xymhguNAIgUyUF7cGNY",
      type: "text",
      props: {
        color: "black",
        size: "m",
        w: 267.61932373046875,
        text: "Welcome To branc",
        font: "draw",
        align: "middle",
        autoSize: true,
        scale: 1.9129384582204882,
      },
      parentId: "page:page",
      index: "a2",
      typeName: "shape",
    },
    
"shape:6iIAjPAk1CBElMTdG9nt2": {
  x: 571.9004361882053,
  y: 492.09983654830467,
  rotation: 0,
  isLocked: false,
  opacity: 1,
  meta: {},
  id: "shape:6iIAjPAk1CBElMTdG9nt2",
  type: "chat",
  parentId: "page:page",
  index: "a6",
  props: {
    w: 300,
    h: 200,
    dateCreated: 1717033314519,
    prompt: "",
    response: "",
    branchType: "normal",
    color: "black",
    dash: "draw",
  },
  typeName: "shape",
},
  },
  schema: {
    schemaVersion: 2,
    sequences: {
      "com.tldraw.store": 4,
      "com.tldraw.asset": 1,
      "com.tldraw.camera": 1,
      "com.tldraw.document": 2,
      "com.tldraw.instance": 24,
      "com.tldraw.instance_page_state": 5,
      "com.tldraw.page": 1,
      "com.tldraw.instance_presence": 5,
      "com.tldraw.pointer": 1,
      "com.tldraw.shape": 4,
      "com.tldraw.asset.bookmark": 1,
      "com.tldraw.asset.image": 3,
      "com.tldraw.asset.video": 3,
      "com.tldraw.shape.group": 0,
      "com.tldraw.shape.text": 1,
      "com.tldraw.shape.bookmark": 2,
      "com.tldraw.shape.draw": 1,
      "com.tldraw.shape.geo": 8,
      "com.tldraw.shape.note": 6,
      "com.tldraw.shape.line": 4,
      "com.tldraw.shape.frame": 0,
      "com.tldraw.shape.arrow": 3,
      "com.tldraw.shape.highlight": 0,
      "com.tldraw.shape.embed": 4,
      "com.tldraw.shape.image": 3,
      "com.tldraw.shape.video": 2,
      "com.tldraw.shape.chat": 0,
    },
  },
};
